production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: daredevils_development
  pool: 5
  host: localhost
  username: postgres
  password: root

test:
  adapter: postgresql
  database: daredevils_test
  pool: 5
  host: localhost
  username: postgres
  password: root